---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqldb
subsets:
  - addresses:
      - ip: 192.168.0.118
    ports:
      - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: spring-batch-prmetheus-grafana-service
spec:
  selector:
    app: spring-batch-prmetheus-grafana-app
  ports:
    - name: http
      port: 8082
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-batch-prmetheus-grafana
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-batch-prmetheus-grafana-app
  template:
    metadata:
      labels:
        app: spring-batch-prmetheus-grafana-app
    spec:
      containers:
        - name: spring-batch-prmetheus-grafana
          image: felipemira/spring-batch-prometheus-grafana:v3
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080