version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin123456"
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER_HOST: '%'
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "sa123456"
      MYSQL_DATABASE: spring_batch
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_storage:/var/lib/mysql
    networks:
      - observability-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 3307:8080
    networks:
      - observability-network
      
  grafana:
    image: grafana/grafana:9.2.0
    container_name: grafana
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - observability-network
    labels:
      org.label-schema.group: "observability"

volumes:
  grafana_storage: {}
  mysqldb_storage: {}
    

networks: 
  observability-network:
    driver: bridge