spring:
  application:
    name: Spring Batch Processing Demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/spring_batch?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    name: MySQL Connection
    username: sa
    password: sa123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    show_sql: false
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  jackson:
        serialization:
          write_dates_as_timestamps: false
  batch:
    initialize-schema: always
    job:
      enabled: false
  sql:
    init:
      mode: always
server:
  port: 8080
debug: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus